use serde_json::json;

use crate::{ProjectionRecord, escape_json};

pub(crate) struct ProjectionRecordRow {
    pub(crate) kind: &'static str,
    pub(crate) record_id: String,
    pub(crate) a: Option<String>,
    pub(crate) b: Option<String>,
    pub(crate) c: Option<String>,
    pub(crate) d: Option<String>,
    pub(crate) e: Option<String>,
    pub(crate) f: Option<String>,
    pub(crate) g: Option<String>,
    pub(crate) h: Option<String>,
    pub(crate) payload_json: String,
}

pub(crate) fn projection_record_to_row(record: &ProjectionRecord) -> ProjectionRecordRow {
    match record {
        ProjectionRecord::Project(project) => ProjectionRecordRow {
            kind: "project",
            record_id: project.project_id.to_string(),
            a: Some(project.name.clone()),
            b: Some(project.status.clone()),
            c: None,
            d: None,
            e: None,
            f: None,
            g: None,
            h: None,
            payload_json: "{}".to_string(),
        },
        ProjectionRecord::Task(task) => ProjectionRecordRow {
            kind: "task",
            record_id: task.task_id.to_string(),
            a: Some(task.project_id.to_string()),
            b: Some(task.title.clone()),
            c: Some(task.capo_execution_status.clone()),
            d: task.active_session_id.as_ref().map(ToString::to_string),
            e: task.latest_summary.clone(),
            f: task.evidence_id.as_ref().map(ToString::to_string),
            g: None,
            h: None,
            payload_json: "{}".to_string(),
        },
        ProjectionRecord::Agent(agent) => ProjectionRecordRow {
            kind: "agent",
            record_id: agent.agent_id.to_string(),
            a: Some(agent.project_id.to_string()),
            b: Some(agent.name.clone()),
            c: Some(agent.status.clone()),
            d: agent.current_session_id.as_ref().map(ToString::to_string),
            e: None,
            f: None,
            g: None,
            h: None,
            payload_json: "{}".to_string(),
        },
        ProjectionRecord::Session(session) => ProjectionRecordRow {
            kind: "session",
            record_id: session.session_id.to_string(),
            a: Some(session.project_id.to_string()),
            b: session.task_id.as_ref().map(ToString::to_string),
            c: Some(session.agent_id.to_string()),
            d: Some(session.title.clone()),
            e: Some(session.status.clone()),
            f: Some(session.current_goal.clone()),
            g: session.latest_summary.clone(),
            h: session.latest_confidence.map(|value| value.to_string()),
            // Positional slots a..h are exhausted, so the adapter-owned external
            // session ref rides in the payload to survive projection rebuilds.
            payload_json: json!({ "external_session_ref": session.external_session_ref })
                .to_string(),
        },
        ProjectionRecord::Run(run) => ProjectionRecordRow {
            kind: "run",
            record_id: run.run_id.to_string(),
            a: Some(run.session_id.to_string()),
            b: Some(run.status.clone()),
            c: run.recovery_of_run_id.as_ref().map(ToString::to_string),
            d: None,
            e: None,
            f: None,
            g: None,
            h: None,
            payload_json: "{}".to_string(),
        },
        ProjectionRecord::CapabilityGrant(grant) => ProjectionRecordRow {
            kind: "capability_grant",
            record_id: grant.capability_grant_id.clone(),
            a: Some(grant.capability_profile_id.clone()),
            b: Some(grant.scope_json.clone()),
            c: Some(grant.effect.clone()),
            d: Some(grant.subject_json.clone()),
            e: Some(grant.decision_source.clone()),
            f: Some(grant.persistence.clone()),
            g: Some(grant.explanation.clone()),
            h: None,
            // SG3: positional slots a..g are exhausted, so the grant lifecycle
            // timestamps ride in the payload to survive projection rebuilds.
            payload_json: json!({
                "created_at": grant.created_at,
                "expires_at": grant.expires_at,
                "revoked_at": grant.revoked_at,
            })
            .to_string(),
        },
        ProjectionRecord::WorkspaceLease(lease) => ProjectionRecordRow {
            kind: "workspace_lease",
            record_id: lease.workspace_lease_id.clone(),
            a: Some(lease.project_id.to_string()),
            b: Some(lease.holder_session_id.to_string()),
            c: lease.holder_run_id.as_ref().map(ToString::to_string),
            d: Some(lease.status.clone()),
            e: lease.acquired_at.clone(),
            f: lease.released_at.clone(),
            g: Some(lease.release_reason.clone()),
            h: None,
            payload_json: "{}".to_string(),
        },
        ProjectionRecord::PermissionApproval(approval) => ProjectionRecordRow {
            kind: "permission_approval",
            record_id: approval.approval_id.clone(),
            a: Some(approval.project_id.to_string()),
            b: approval.session_id.as_ref().map(ToString::to_string),
            c: approval.tool_call_id.as_ref().map(ToString::to_string),
            d: Some(approval.capability_profile_id.clone()),
            e: Some(approval.status.clone()),
            f: approval.decision.clone(),
            g: approval.capability_grant_id.clone(),
            h: Some(approval.scope_json.clone()),
            payload_json: format!(
                "{{\"subject_json\":{},\"requested_by\":\"{}\",\"reason\":\"{}\"}}",
                approval.subject_json,
                escape_json(&approval.requested_by),
                escape_json(&approval.reason)
            ),
        },
        ProjectionRecord::ConnectivityExposure(exposure) => ProjectionRecordRow {
            kind: "connectivity_exposure",
            record_id: exposure.exposure_id.clone(),
            a: Some(exposure.project_id.to_string()),
            b: Some(exposure.connectivity_endpoint_id.clone()),
            c: Some(exposure.status.clone()),
            d: exposure.capability_grant_id.clone(),
            e: Some(exposure.health_status.clone()),
            f: Some(exposure.reachable.to_string()),
            g: exposure.revoked_at.clone(),
            h: Some(exposure.permission_scope.clone()),
            payload_json: json!({
                "owner_kind": exposure.owner_kind,
                "owner_id": exposure.owner_id,
                "channel_kind": exposure.channel_kind,
                "exposure": exposure.exposure,
            })
            .to_string(),
        },
        ProjectionRecord::RuntimeTarget(target) => ProjectionRecordRow {
            kind: "runtime_target",
            record_id: target.runtime_target_id.clone(),
            a: Some(target.project_id.to_string()),
            b: Some(target.name.clone()),
            c: Some(target.runner_kind.clone()),
            d: Some(target.status.clone()),
            e: target.connectivity_endpoint_id.clone(),
            f: Some(target.capability_profile_id.clone()),
            g: Some(target.workspace_root.clone()),
            h: Some(target.artifact_root.clone()),
            payload_json: json!({
                "default_cwd": target.default_cwd,
            })
            .to_string(),
        },
        ProjectionRecord::AdapterReadiness(readiness) => ProjectionRecordRow {
            kind: "adapter_readiness",
            record_id: readiness.adapter_kind.clone(),
            a: Some(readiness.project_id.to_string()),
            b: Some(readiness.program.clone()),
            c: Some(readiness.opt_in_env.clone()),
            d: Some(readiness.opted_in.to_string()),
            e: Some(readiness.smoke_status.clone()),
            f: Some(readiness.credential_policy.clone()),
            g: Some(readiness.expected_marker.clone()),
            h: readiness.dogfood_blocker.clone(),
            payload_json: json!({
                "env_allowlist_count": readiness.env_allowlist_count,
                "redaction_rule_count": readiness.redaction_rule_count,
                "output_limit_bytes": readiness.output_limit_bytes,
            })
            .to_string(),
        },
        ProjectionRecord::AdapterSmokeReport(report) => ProjectionRecordRow {
            kind: "adapter_smoke_report",
            record_id: report.smoke_report_id.clone(),
            a: Some(report.project_id.to_string()),
            b: Some(report.adapter_kind.clone()),
            c: Some(report.smoke_status.clone()),
            d: Some(report.credential_scan_status.clone()),
            e: Some(report.marker_found.to_string()),
            f: report.artifact_root.clone(),
            g: Some(report.dogfood_readiness_effect.clone()),
            h: None,
            payload_json: json!({
                "reason": report.reason,
            })
            .to_string(),
        },
        ProjectionRecord::AdapterDispatchPlan(plan) => ProjectionRecordRow {
            kind: "adapter_dispatch_plan",
            record_id: plan.dispatch_plan_id.clone(),
            a: Some(plan.project_id.to_string()),
            b: Some(plan.adapter_kind.clone()),
            c: Some(plan.agent_id.to_string()),
            d: Some(plan.session_id.to_string()),
            e: Some(plan.run_id.to_string()),
            f: Some(plan.status.clone()),
            g: Some(plan.provider_cli_executed.to_string()),
            h: Some(plan.runtime_prompt_policy.clone()),
            payload_json: json!({
                "provider_kind": plan.provider_kind,
                "credential_scope": plan.credential_scope,
                "agent_name": plan.agent_name,
                "runtime_program": plan.runtime_program,
                "runtime_arg_count": plan.runtime_arg_count,
                "runtime_cwd": plan.runtime_cwd,
                "artifact_root": plan.artifact_root,
                "request_env_count": plan.request_env_count,
                "env_allowlist_count": plan.env_allowlist_count,
                "redaction_rule_count": plan.redaction_rule_count,
                "stdout_format": plan.stdout_format,
                "stderr_policy": plan.stderr_policy,
            })
            .to_string(),
        },
        ProjectionRecord::AdapterDispatchGate(gate) => ProjectionRecordRow {
            kind: "adapter_dispatch_gate",
            record_id: gate.dispatch_gate_id.clone(),
            a: Some(gate.project_id.to_string()),
            b: Some(gate.dispatch_plan_id.clone()),
            c: Some(gate.adapter_kind.clone()),
            d: Some(gate.provider_cli_execution_allowed.to_string()),
            e: Some(gate.status.clone()),
            f: Some(gate.required_dogfood_gate.clone()),
            g: Some(gate.provider_cli_executed.to_string()),
            h: Some(gate.runtime_prompt_policy.clone()),
            payload_json: json!({
                "reason_codes": gate.reason_codes,
            })
            .to_string(),
        },
        ProjectionRecord::AdapterDispatchReplay(replay) => ProjectionRecordRow {
            kind: "adapter_dispatch_replay",
            record_id: replay.dispatch_replay_id.clone(),
            a: Some(replay.project_id.to_string()),
            b: Some(replay.dispatch_plan_id.clone()),
            c: Some(replay.dispatch_gate_id.clone()),
            d: Some(replay.adapter_kind.clone()),
            e: Some(replay.session_id.to_string()),
            f: Some(replay.run_id.to_string()),
            g: Some(replay.provider_cli_executed.to_string()),
            h: Some(replay.raw_content_policy.clone()),
            payload_json: json!({
                "fixture_path": replay.fixture_path,
                "fixture_hash": replay.fixture_hash,
                "input_event_count": replay.input_event_count,
                "appended_event_count": replay.appended_event_count,
                "tool_event_count": replay.tool_event_count,
                "summary_event_count": replay.summary_event_count,
                "completed_turn_count": replay.completed_turn_count,
            })
            .to_string(),
        },
        ProjectionRecord::AdapterDispatchExecutionRequest(request) => ProjectionRecordRow {
            kind: "adapter_dispatch_execution_request",
            record_id: request.execution_request_id.clone(),
            a: Some(request.project_id.to_string()),
            b: Some(request.dispatch_plan_id.clone()),
            c: Some(request.dispatch_gate_id.clone()),
            d: Some(request.adapter_kind.clone()),
            e: Some(request.provider_cli_execution_allowed.to_string()),
            f: Some(request.status.clone()),
            g: Some(request.provider_cli_executed.to_string()),
            h: Some(request.runtime_prompt_policy.clone()),
            payload_json: json!({
                "opt_in_env": request.opt_in_env,
                "reason_codes": request.reason_codes,
            })
            .to_string(),
        },
        ProjectionRecord::AdapterDispatchExecution(execution) => ProjectionRecordRow {
            kind: "adapter_dispatch_execution",
            record_id: execution.dispatch_execution_id.clone(),
            a: Some(execution.project_id.to_string()),
            b: Some(execution.dispatch_plan_id.clone()),
            c: Some(execution.execution_request_id.clone()),
            d: Some(execution.adapter_kind.clone()),
            e: Some(execution.session_id.to_string()),
            f: Some(execution.run_id.to_string()),
            g: Some(execution.provider_cli_executed.to_string()),
            h: Some(execution.status.clone()),
            payload_json: json!({
                "provider_cli_execution_allowed": execution.provider_cli_execution_allowed,
                "exit_code": execution.exit_code,
                "runtime_process_ref": execution.runtime_process_ref,
                "stdout_artifact_id": execution.stdout_artifact_id,
                "stderr_artifact_id": execution.stderr_artifact_id,
                "artifact_root": execution.artifact_root,
                "credential_scan_status": execution.credential_scan_status,
                "raw_prompt_policy": execution.raw_prompt_policy,
                "raw_output_policy": execution.raw_output_policy,
                "reason_codes": execution.reason_codes,
            })
            .to_string(),
        },
        ProjectionRecord::AdapterDispatchPromptSource(source) => ProjectionRecordRow {
            kind: "adapter_dispatch_prompt_source",
            record_id: source.prompt_source_id.clone(),
            a: Some(source.project_id.to_string()),
            b: Some(source.dispatch_plan_id.clone()),
            c: Some(source.prompt_hash.clone()),
            d: Some(source.source_kind.clone()),
            e: source.source_ref.clone(),
            f: source.source_hash.clone(),
            g: Some(source.materialization_status.clone()),
            h: Some(source.raw_prompt_policy.clone()),
            payload_json: "{}".to_string(),
        },
        ProjectionRecord::AdapterDispatchPromptMaterialization(materialization) => {
            ProjectionRecordRow {
                kind: "adapter_dispatch_prompt_materialization",
                record_id: materialization.materialization_id.clone(),
                a: Some(materialization.project_id.to_string()),
                b: Some(materialization.dispatch_plan_id.clone()),
                c: Some(materialization.prompt_source_id.clone()),
                d: Some(materialization.source_kind.clone()),
                e: Some(materialization.expected_prompt_hash.clone()),
                f: materialization.materialized_prompt_hash.clone(),
                g: Some(materialization.status.clone()),
                h: Some(materialization.raw_prompt_policy.clone()),
                payload_json: json!({
                    "source_ref": materialization.source_ref,
                    "expected_source_hash": materialization.expected_source_hash,
                    "observed_source_hash": materialization.observed_source_hash,
                    "reason_codes": materialization.reason_codes,
                })
                .to_string(),
            }
        }
        ProjectionRecord::ToolCall(tool_call) => ProjectionRecordRow {
            kind: "tool_call",
            record_id: tool_call.tool_call_id.to_string(),
            a: Some(tool_call.session_id.to_string()),
            b: tool_call.turn_id.clone(),
            c: Some(tool_call.tool_name.clone()),
            d: Some(tool_call.tool_origin.clone()),
            e: Some(tool_call.status.clone()),
            f: tool_call.input_artifact_id.clone(),
            g: tool_call.output_artifact_id.clone(),
            h: None,
            // ACI7: the per-call provenance + timing travels in the payload (the
            // `a..h` slots are spent), so a replay rebuilds the queryable chain
            // identically.
            payload_json: json!({
                "correlation_id": tool_call.provenance.correlation_id,
                "permission_decision_id": tool_call.provenance.permission_decision_id,
                "capability_grant_use_id": tool_call.provenance.capability_grant_use_id,
                "started_at": tool_call.provenance.started_at,
                "completed_at": tool_call.provenance.completed_at,
            })
            .to_string(),
        },
        ProjectionRecord::ToolObservation(observation) => ProjectionRecordRow {
            kind: "tool_observation",
            record_id: observation.tool_observation_id.clone(),
            a: Some(observation.session_id.to_string()),
            b: observation.tool_call_id.as_ref().map(ToString::to_string),
            c: Some(observation.source.clone()),
            d: observation.external_tool_ref.clone(),
            e: Some(observation.tool_name.clone()),
            f: Some(observation.observed_status.clone()),
            g: Some(observation.instrumentation_level.clone()),
            h: Some(observation.confidence.clone()),
            payload_json: json!({
                "raw_event_hash": observation.raw_event_hash,
                "artifact_id": observation.artifact_id,
            })
            .to_string(),
        },
        ProjectionRecord::MemoryPacketRef(packet) => ProjectionRecordRow {
            kind: "memory_packet",
            record_id: packet.memory_packet_id.to_string(),
            a: Some(packet.project_id.to_string()),
            b: packet.task_id.as_ref().map(ToString::to_string),
            c: packet.agent_id.as_ref().map(ToString::to_string),
            d: packet.session_id.as_ref().map(ToString::to_string),
            e: packet.run_id.as_ref().map(ToString::to_string),
            f: packet.turn_id.clone(),
            g: packet.packet_artifact_id.clone(),
            h: Some(packet.purpose.clone()),
            payload_json: "{}".to_string(),
        },
        ProjectionRecord::MemoryRecord(memory_record) => ProjectionRecordRow {
            kind: "memory_record",
            record_id: memory_record.memory_record_id.clone(),
            a: Some(memory_record.project_id.to_string()),
            b: Some(memory_record.scope.clone()),
            c: Some(memory_record.scope_owner_ref.clone()),
            d: memory_record.subject_ref.clone(),
            e: Some(memory_record.sensitivity_classification.clone()),
            f: Some(memory_record.record_kind.clone()),
            g: Some(memory_record.review_state.clone()),
            h: Some(memory_record.source_count.to_string()),
            payload_json: json!({
                "subject": memory_record.subject,
                "predicate": memory_record.predicate,
                "object": memory_record.object,
                "body": memory_record.body,
                "confidence": memory_record.confidence,
                "valid_from": memory_record.valid_from,
                "valid_until": memory_record.valid_until,
                "supersedes_memory_record_id": memory_record.supersedes_memory_record_id,
                "revoked_by_memory_record_id": memory_record.revoked_by_memory_record_id,
                "redaction_state": memory_record.redaction_state,
                "invalidated_at": memory_record.invalidated_at,
                "invalidation_reason": memory_record.invalidation_reason,
                "packet_item_ref": memory_record.packet_item_ref,
            })
            .to_string(),
        },
        ProjectionRecord::MemorySource(source) => ProjectionRecordRow {
            kind: "memory_source",
            record_id: source.memory_source_id.clone(),
            a: Some(source.memory_record_id.clone()),
            b: Some(source.source_kind.clone()),
            c: source.source_event_id.clone(),
            d: source.source_artifact_id.clone(),
            e: source.source_path.clone(),
            f: source.source_anchor.clone(),
            g: source.source_content_hash.clone(),
            h: source.source_sequence.map(|value| value.to_string()),
            payload_json: json!({
                "quote_artifact_id": source.quote_artifact_id,
                "observed_at": source.observed_at,
            })
            .to_string(),
        },
        ProjectionRecord::Evidence(evidence) => ProjectionRecordRow {
            kind: "evidence",
            record_id: evidence.evidence_id.to_string(),
            a: Some(evidence.project_id.to_string()),
            b: evidence.task_id.as_ref().map(ToString::to_string),
            c: evidence.session_id.as_ref().map(ToString::to_string),
            d: evidence.run_id.as_ref().map(ToString::to_string),
            e: Some(evidence.kind.clone()),
            f: evidence.artifact_id.clone(),
            g: Some(evidence.confidence.to_string()),
            h: None,
            payload_json: "{}".to_string(),
        },
        ProjectionRecord::TaskOutcomeReport(report) => ProjectionRecordRow {
            kind: "task_outcome_report",
            record_id: report.task_outcome_report_id.clone(),
            a: Some(report.project_id.to_string()),
            b: Some(report.task_id.to_string()),
            c: Some(report.session_id.to_string()),
            d: Some(report.run_id.to_string()),
            e: Some(report.outcome_status.clone()),
            f: Some(report.started_sequence.to_string()),
            g: Some(report.completed_sequence.to_string()),
            h: Some(report.duration_sequence_span.to_string()),
            payload_json: json!({
                "action_count": report.action_count,
                "tool_call_count": report.tool_call_count,
                "evidence_count": report.evidence_count,
                "memory_packet_count": report.memory_packet_count,
                "confidence": report.confidence,
                "blocker": report.blocker,
                "review_outcome": report.review_outcome,
                "report_artifact_id": report.report_artifact_id,
            })
            .to_string(),
        },
        ProjectionRecord::ReviewFinding(finding) => ProjectionRecordRow {
            kind: "review_finding",
            record_id: finding.review_finding_id.clone(),
            a: Some(finding.project_id.to_string()),
            b: Some(finding.task_id.to_string()),
            c: Some(finding.session_id.to_string()),
            d: finding.run_id.as_ref().map(ToString::to_string),
            e: finding.tool_call_id.as_ref().map(ToString::to_string),
            f: finding.workpad_task_id.clone(),
            g: Some(finding.finding_kind.clone()),
            h: Some(finding.status.clone()),
            payload_json: json!({
                "reviewer": finding.reviewer,
                "severity": finding.severity,
                "summary": finding.summary,
                "evidence_artifact_id": finding.evidence_artifact_id,
                "follow_up": finding.follow_up,
            })
            .to_string(),
        },
        ProjectionRecord::SourceBinding(binding) => ProjectionRecordRow {
            kind: "source_binding",
            record_id: binding.source_binding_id.clone(),
            a: Some(binding.project_id.to_string()),
            b: Some(binding.task_id.to_string()),
            c: Some(binding.source_kind.clone()),
            d: Some(binding.source_task_id.clone()),
            e: Some(binding.source_path.clone()),
            f: Some(binding.source_anchor.clone()),
            g: Some(binding.source_hash.clone()),
            h: Some(binding.binding_status.clone()),
            payload_json: "{}".to_string(),
        },
        ProjectionRecord::WorkpadIndexReset(reset) => ProjectionRecordRow {
            kind: "workpad_index_reset",
            record_id: reset.project_id.to_string(),
            a: Some(reset.observed_unix.to_string()),
            b: None,
            c: None,
            d: None,
            e: None,
            f: None,
            g: None,
            h: None,
            payload_json: "{}".to_string(),
        },
        ProjectionRecord::WorkpadFile(file) => ProjectionRecordRow {
            kind: "workpad_file",
            record_id: file.path.clone(),
            a: Some(file.project_id.to_string()),
            b: Some(file.content_hash.clone()),
            c: Some(file.headings.clone()),
            d: file.objective.clone(),
            e: Some(file.observed_unix.to_string()),
            f: None,
            g: None,
            h: None,
            payload_json: "{}".to_string(),
        },
        ProjectionRecord::WorkpadTask(task) => ProjectionRecordRow {
            kind: "workpad_task",
            record_id: task.workpad_task_id.clone(),
            a: Some(task.project_id.to_string()),
            b: Some(task.path.clone()),
            c: Some(task.source_anchor.clone()),
            d: Some(task.title.clone()),
            e: Some(task.observed_status.clone()),
            f: Some(task.capo_execution_status.clone()),
            g: Some(task.observed_unix.to_string()),
            h: None,
            payload_json: "{}".to_string(),
        },
    }
}
